import Head from 'next/head'
import NavBar from '../components/NavBar';
import Home from './HomeScreen';
export default function App() {
  return (<>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   <NavBar />
   <Home />
      </>
  )
}
