import Head from "next/head";
import { useContext } from "react";
import NavBar from "../components/NavBar";
import Home from "./HomeScreen";
import ThemeContext from "../public/theme-context";
export default function App() {
  const theme = useContext(ThemeContext);
  return (
    <>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <NavBar />
        <Home />
      </div>
    </>
  );
}
